Johann-S/bs-customizer

src/main.css
Add some margin between button and footer on small viewports:
=> Margin update

index.html
I think minifying should be enabled by default. Thoughts?
=> Check minify by default

src/build.js, src/lib/sass.worker.js, src/util.js
=> temporary fix for Edge to build sass

.appveyor.yml, README.md, package.json
=> Add CI support

index.html, src/index.js, webpack.config.js
Make our build button bigger, and change it to submit type
Fixes: #20
=> Change build button

README.md, package-lock.json, package.json, src/build.js, src/dialog-loader.js, src/file-util.js, src/index.js, src/plugins.js, src/util.js, webpack.config.js
=> use standard js to lint our js files

src/index.js
Adding the handler on the form submit would make more sense imo.
=> Form submit instead of button click event

package.json, webpack.config.js
=> minify our css with clean-css

src/index.html, src/js/index.js, src/js/toggler.js
=> toggle all elements

package-lock.json, package.json, webpack.config.js
=> Add clean-webpack-plugin.

src/index.html, src/js/index.js, src/js/toggler.js
Simplified version of the _toggle all_ functionality.
=> Simplify toggler

src/js/build.js
=> apply sass config

src/index.html
I don't know if it fix this : https://github.com/Johann-S/bs-customizer/issues/17 or not 🤔
=> add a bit of information

src/index.html
=> add a meta description

src/index.html, src/js/index.js, src/js/toggler.js
If we check popover we must check tooltip too, because popover inherit from tooltip
=> check tooltip if we check popover

package-lock.json, package.json
It uses vnu-jar API so no Java required.
=> Add HTML validation with html-validator.

package-lock.json, package.json, src/css/main.css, src/index.html, src/js/dialog-loader.js, webpack.config.js
I removed `Boxicons` and now we use `svg`, but I'm unable to fix the rotation of the loader 😟 
Maybe @XhmikosR or @MartijnCuppens you can help me ?
Fixes: #7
=> use svg icons instead of fonts

src/index.html, src/js/build.js, src/js/config.js, src/js/index.js, src/js/plugins.js, webpack.config.js
=> specify bootstrap version and add header

package-lock.json, package.json, src/index.html, src/js/config.js, src/js/plugins.js, src/js/util.js
=> update to 4.2.1

src/index.html, src/js/build.js, src/js/config.js, src/js/plugins.js, src/js/util.js
~~To do after that update our deps~~
Fixes: #91
=> update to bootstrap v4.3.1
